### ISSUE TITLE
Coverage on dynamic secrets and ...

### ISSUE THREAD

**Issue by mprkatti** [data-on-k8s-book/outline#1]
Hi Jeff,

couple of things.

1. Coverage on dynamic secrets will also be helpful [sorry if it is already covered and I missed it]. That is db passwords that are only valid for the length of the session.  

2. while I understand Cassandra already provides responses in single digit, millisecond range, is it wise to consider putting a cache layer in the front and if so what choices make sound design sense.

2. Full Text search on DSE ?

Cheers!!
Prasad Katti

**Comment by pmcfadin** [comment]
Hi Prasad!

Thanks for the comments. On #1 definitely in scope for this book. Kubernetes has a well defined method of managing secrets. We'll need to make sure and cover that thoroughly as you deploy various infrastructure. Your specific use case of dynamic secrets is interesting. Can you provide an example of where that is done now?

For #2 and #3 we are trying hard to not make this a book about only Cassandra. #2 would be a use case that may be in scope but #3 is about using specific features in one database that we are strictly trying to stay clear of for now. 

Thanks!

Patrick

**Comment by mprkatti** [comment]
Thanks Patrick for your response.  I will come back to you on the dynamic secrets part.
