### ISSUE TITLE
Would like a translation

### ISSUE THREAD

**Issue by tzkoba** [data-on-k8s-book/outline#2]
I think this book will be great.
When I introduced this outline on SNS, it received a lot of feedback from Kubernetes users in Japan.

Are there any plans for a Japanese or other translation?
(I was involved in the Japanese translation of Database Internals.)

**Comment by pmcfadin** [comment]
O'Reilly ultimately makes the choice on translation but they have a good record of multiple language translations. 

Any feedback we can incorporate?
